name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV
          NOTIFY_API_KEY=$(<dev-notify-api-key)
          echo "NOTIFY_API_KEY=$NOTIFY_API_KEY" >> $GITHUB_ENV
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install virtual environment with dev dependencies
        run: make install-dev
      - name: Running lint tests
        run: make lint
      - name: Running unit tests
        run: make test